/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIdRouteImport } from './routes/plans/$id'
import { Route as PlansIdActivityIdRouteImport } from './routes/plans/$id/$activityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIdRoute = PlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIdActivityIdRoute = PlansIdActivityIdRouteImport.update({
  id: '/$activityId',
  path: '/$activityId',
  getParentRoute: () => PlansIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$id': typeof PlansIdRouteWithChildren
  '/plans/$id/$activityId': typeof PlansIdActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$id': typeof PlansIdRouteWithChildren
  '/plans/$id/$activityId': typeof PlansIdActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$id': typeof PlansIdRouteWithChildren
  '/plans/$id/$activityId': typeof PlansIdActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plans/$id' | '/plans/$id/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plans/$id' | '/plans/$id/$activityId'
  id: '__root__' | '/' | '/plans/$id' | '/plans/$id/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansIdRoute: typeof PlansIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$id': {
      id: '/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof PlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$id/$activityId': {
      id: '/plans/$id/$activityId'
      path: '/$activityId'
      fullPath: '/plans/$id/$activityId'
      preLoaderRoute: typeof PlansIdActivityIdRouteImport
      parentRoute: typeof PlansIdRoute
    }
  }
}

interface PlansIdRouteChildren {
  PlansIdActivityIdRoute: typeof PlansIdActivityIdRoute
}

const PlansIdRouteChildren: PlansIdRouteChildren = {
  PlansIdActivityIdRoute: PlansIdActivityIdRoute,
}

const PlansIdRouteWithChildren =
  PlansIdRoute._addFileChildren(PlansIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansIdRoute: PlansIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
